### ISSUE TITLE
Tests no se ejecutan (y están incompletos)

### ISSUE THREAD

**Issue by ncuesta** [fedegratti/e_billing#1]
Los tests no ejecutan, tiran este error antes:

``` console
$ rake test
rake aborted!
NoMethodError: undefined method `setup' for RSpec::ExampleGroups::NewClient:Class
test/models/new_client_test.rb:5:in `block in <top (required)>'
test/models/new_client_test.rb:3:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => test:run
(See full trace by running task with --trace)
```

Intenté corregir el error pero luego los tests ni se ejecutaban. Luego, vi el código y me di cuenta que estaban incompletos. Recomiendo, en caso de seguir con RSpec, configurar correctamente el proyecto primero (Rails no está enterado que tiene que usar RSpec en lugar de MiniTest).

**Comment by ncuesta** [comment]
Corregido.
